### ISSUE TITLE
[Feature request] Please make the map search link international or configurable

### ISSUE THREAD

**Issue by victor-kallai** [aymericdo/google-map-redirection-fixed#1]
Please change the www.google.fr search link to www.google.com or make this configurable from the options.

Thank you.

**Comment by aymericdo** [comment]
Thanks for your comment.

I made this change in this [commit](https://github.com/aymericdo/google-map-redirection-fixed/commit/e3f4678f471e007b8d1bea7996773fa01a25a967) and it's deploy in the 2.4 version 😄
